### ISSUE TITLE
Chybí ikonka poznámek

### ISSUE THREAD

**Issue by zgruza** [seznam/homepage-legacy#1]
Prosím kde najdu tuto ikonku poznámek? Vím, že se jedná o Homepage assets, našel jsem v tomto archivu legacy ikonku poštovní schránky, která byla použita na emailu (jako notifikace) na úvodní stránce. Bylo by možné někde sehnat legacy ikonku poznámek?

![legacy-seznam-email](https://github.com/seznam/homepage-legacy/assets/47500410/96d6c35e-85fa-4ed1-84c5-183a10e6924d)

**Comment by onovy** [comment]
odhaduji, že tato ikona byla v assetech starého emailu, nikoliv homepage.

**Comment by zgruza** [comment]
Píšu na základě toho, že se právě v tomto archivu nachází ikonka , která pochází z emailu (https://github.com/seznam/homepage-legacy/blob/main/frontend-2015/html/img/ico_mail.gif) a nikde archiv legacy emailu nemůžu najít.

**Comment by onovy** [comment]
archiv legacy emailu nemáme. Ikonka emailu z repozitáře legacy HP byla pravděpodobně využita přímo na HP, proto ji máme v legacy HP.
